[versions]
activityCompose = "1.11.0"
agp = "9.0.0"
androidxJunit = "1.3.0"
composeBomVersion = "2025.10.01"
converterGson = "3.0.0"
coreKtxVersion = "1.17.0"
espressoCore = "3.7.0"
itext7Core = "9.3.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.2.1"
appcompat = "1.7.0"
lifecycleLivedataKtx = "2.9.4"
lifecycleViewmodelCompose = "2.9.4"
mapsCompose = "6.12.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
composeBom = "2025.10.01"
lifecycle = "2.8.6"
gson = "2.13.2"
material3 = "1.4.0"
navigationCompose = "2.9.5"
playServicesAuth = "21.4.0"
playServicesMaps = "19.2.0"
playServicesLocation = "21.3.0"
firebaseBom = "34.4.0"
coroutines = "1.10.2"
retrofit = "3.0.0"
runtimeLivedata = "1.9.4"
ui = "1.9.4"
uiTooling = "1.9.4"
uiToolingPreview = "1.9.4"
firebaseAuthKtx = "23.2.1"
firebaseStorageKtx = "21.0.2"
test-ext-junit = "1.3.0"
foundationLayout = "1.9.5"
webkit = "1.14.0"
foundation = "1.10.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom-v20240903 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1131 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "ui" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
google-firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
google-firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
itext7-core = { module = "com.itextpdf:itext7-core", version.ref = "itext7Core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "mapsCompose" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationCompose" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx" }
com-google-firebase-firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
com-google-firebase-firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
itext = { module = "com.itextpdf:itext7-core", version.ref = "itext7Core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "test-ext-junit" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }